# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#a9b665" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword	= { fg = "#a9b665", italic = true }
find_position	= { fg = "#e78a4e", bg = "reset", italic = true }

# Marker
marker_copied	= { fg = "#89b482", bg = "#89b482" }
marker_cut		= { fg = "#d3869b", bg = "#d3869b" }
marker_marked	= { fg = "#83a598", bg = "#83a598" }
marker_selected = { fg = "#fbf1c7", bg = "#fbf1c7" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied	= { fg = "#282828", bg = "#89b482" }
count_cut		= { fg = "#282828", bg = "#d3869b" }
count_selected	= { fg = "#282828", bg = "#fbf1c7" }

# Border
border_symbol = "│"
border_style  = { fg = "#665c54" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#282828", bg = "#a89984", bold = true }
normal_alt  = { fg = "#282828", bg = "#89b482" }

# Select mode
select_main = { fg = "#282828", bg = "#e78a4e", bold = true }
select_alt  = { fg = "#e78a4e", bg = "#282828" }

# Unset mode
unset_main = { fg = "#282828", bg = "#a9b665", bold = true }
unset_alt  = { fg = "#a9b665", bg = "#282828" }

# : }}}


# : Status bar {{{

[status]
separator_open = "\ue0be"
separator_close = "\ue0b8"

# Progress
progress_label	= { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error	= { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#5a524c" }
permissions_r = { fg = "#89b482" }
permissions_w = { fg = "#ea6962" }
permissions_x = { fg = "#89b482" }
permissions_s = { fg = "#5a524c" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#458588" }
active = { fg = "#d3869b", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#ebdbb2" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#d4be98" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#504945" }
title   = {}
hovered = { fg = "#7daea3", underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#3c3836" }
cand = { fg = "#83a598" }
rest = { fg = "#928374" }
desc = { fg = "#fe8019" }
separator = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on = { fg = "#83a598" }
run = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#8ec07c" }
title_warn = { fg = "#fbf1c7" }
title_error = { fg = "#d3869b" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
  { mime = "image/*", fg = "#d8a657" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f9e2af" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ea6962" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#7daea3" },

	# Fallback
  { name = "*", fg = "#ebdbb2" },
  { name = "*/", fg = "#89b482" },
]

# : }}}
