[pyprland]
plugins = [
 "expose",
 "scratchpads",
 "shift_monitors",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class yazi -e yazi"
class = "yazi"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.music]
animation = "fromLeft"
command = "kitty --class ncspot -e ncspot"
class = "ncspot"
size = "35% 80%"
max_size = "1920px 100%"

[scratchpads.pulsemixer]
animation = "fromTop"
command = "kitty --class pulsemixer -e pulsemixer"
class = "pulsemixer"
size = "40% 30%"
max_size = "1920px 100%"
position = "30% 8%"

[scratchpads.bluetuith]
animation = "fromBottom"
command = "kitty --class bluetuith -e bluetuith"
class = "bluetuith"
size = "40% 80%"
max_size = "1920px 100%"
position = "30% 18%"

[scratchpads.proc]
animation = "fromBottom"
command = "kitty --class proc -e btop -p 4"
class = "proc"
size = "75% 65%"
max_size = "1920px 100%"
# [scratchpads.rofi]
# animation = "fromLeft"
# command = "rofi -show combi"
# class = "Rofi"
# size = "15% 60%"
# max_size = "1920px 100%"
