# Theme 
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
[window]
	dynamic_padding = true
# Font config
[font]
	normal = { family = "FiraCode Nerd Font Mono", style = "Regular"}
	bold = { family = "FiraCode Nerd Font Mono", style = "Regular" }
	italic = { family = "FiraCode Nerd Font Mono", style = "Retina" }
	bold_italic= { family = "FiraCode Nerd Font Mono", style = "SemiBold" }

	size = 16.0
